# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0012_auto_20170607_0320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaruant',
            new_name='Restaurant',
        ),
    ]
