# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0014_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', related_query_name='manufacturer_car', to='django_models.Manufacturer'),
        ),
    ]
