# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0019_auto_20170607_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('student3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_models.Lecture3')),
            ],
        ),
    ]
